// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

const _apiKey = "";
const _appId = "";

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _apiKey,
    appId: _appId,
    messagingSenderId: '43724375884',
    projectId: 'pocket-buddy-954e6',
    storageBucket: 'pocket-buddy-954e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _apiKey,
    appId: _appId,
    messagingSenderId: '43724375884',
    projectId: 'pocket-buddy-954e6',
    storageBucket: 'pocket-buddy-954e6.appspot.com',
    androidClientId:
        '43724375884-cvp8276hbcq8gbjkprjdso9514gk1khu.apps.googleusercontent.com',
    iosClientId:
        '43724375884-f6650nmf6pru174ttak74h6h3960codm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketBuddyNew',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _apiKey,
    appId: _appId,
    messagingSenderId: '43724375884',
    projectId: 'pocket-buddy-954e6',
    authDomain: 'pocket-buddy-954e6.firebaseapp.com',
    storageBucket: 'pocket-buddy-954e6.appspot.com',
    measurementId: 'G-GWVYSCWD1S',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _apiKey,
    appId: _appId,
    messagingSenderId: '43724375884',
    projectId: 'pocket-buddy-954e6',
    storageBucket: 'pocket-buddy-954e6.appspot.com',
    androidClientId:
        '43724375884-cvp8276hbcq8gbjkprjdso9514gk1khu.apps.googleusercontent.com',
    iosClientId:
        '43724375884-f6650nmf6pru174ttak74h6h3960codm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketBuddyNew',
  );
}
